version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ../src:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
